version: "3.8"

services:
  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: $${process.env.POSTGRES_USER}
      POSTGRES_PASSWORD: $${process.env.POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - local_pgdb:/var/lib/postgresql/data
    restart: always

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: $${process.env.PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: $${process.env.PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - local_pgadmin:/var/lib/pgadmin
    restart: always
    
volumes:
  local_pgdb:
  local_pgadmin: